### ISSUE TITLE
【积分】积分商城中积分兑换时，提示信息应该由英文改为中文

### ISSUE THREAD

**Issue by Zhangliling** [starcwl/aihangbugs#7]

**Comment by starcwl** [comment]
请补一张图～

**Comment by Zhangliling** [comment]
![2016-02-26 14 45 17](https://cloud.githubusercontent.com/assets/15758940/13345343/0db788fa-dc99-11e5-985c-fcb053ca0298.png)
![2016-02-26 14 45 43](https://cloud.githubusercontent.com/assets/15758940/13345361/22121144-dc99-11e5-943e-015221659dba.png)

**Comment by Zhangliling** [comment]
积分不足的情况还没有修改。
