### ISSUE TITLE
【积分】积分商城注册时，注册成功时应该提示一个注册成功的提示框

### ISSUE THREAD

**Issue by Zhangliling** [starcwl/aihangbugs#8]

**Comment by starcwl** [comment]
注册成功 首页直接登录，是否需要确认提示框？

**Comment by Zhangliling** [comment]
有一个确认登录对话框跳转过去是不是更好？
![2016-02-27 09 30 41](https://cloud.githubusercontent.com/assets/15758940/13369821/01568790-dd35-11e5-8baf-d02731f82637.png)
